name: "Build revxlp (original)"
on: 
  push:
    paths:
      - 'revxlp_original/**'
  pull_request:
    paths:
      - 'revxlp_original/**'

jobs:
  build_revxlp_original:
    uses: iamajoe/keyboards/.github/workflows/build_user_config.yml@main
    with:
       archive_name: "revxlp_original_firmware"
       work_dir: "./revxlp_original"
