on: 
  push:
    paths:
      # - 'revxlp/**'
  pull_request:
    paths:
      # - 'revxlp/**'

jobs:
  build_revxlp:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
       build_matrix_path: "./revxlp/build.yaml"
       config_path: "./revxlp/config"
       fallback_binary: "./revxlp/bin"
