name: "Build revxlp (joe)"
on: 
  push:
    paths:
      - '.github/workflows/kb_revxlp_joe.yml'
      - 'boards/revxlp_joe/**'
  pull_request:
    paths:
      - '.github/workflows/kb_revxlp_joe.yml'
      - 'boards/revxlp_joe/**'

jobs:
  build_revxlp_joe:
    uses: iamajoe/keyboards/.github/workflows/build_user_config.yml@main
    with:
       build_matrix_path: "boards/revxlp_joe/build.yaml"
       config_path: "."
       archive_name: "revxlp_joe_firmware"
       # work_dir: "./revxlp_joe"
  # TODO: fix release, not being able to download the firmware artifact
  # release_revxlp_joe:
  #   if: github.event.pull_request.merged == true && github.base_ref == 'main'
  #   needs: build_revxlp_joe
  #   uses: iamajoe/keyboards/.github/workflows/release_user_config.yml@main
  #   with:
  #     archive_name: "revxlp_joe_firmware"
