name: "Build revxlp (original)"
on: 
  push:
    paths:
      - '.github/workflows/build_user_config.yml'
      - '.github/workflows/kb_revxlp_original.yml'
      - 'boards/shields/revxlp/**'
  pull_request:
    paths:
      - '.github/workflows/build_user_config.yml'
      - '.github/workflows/kb_revxlp_original.yml'
      - 'boards/shields/revxlp/**'

jobs:
  build:
    uses: iamajoe/keyboards/.github/workflows/build_user_config.yml@diff_structure
    with:
       shield: "revxlp"
  # TODO: fix release, not being able to download the firmware artifact
  # release_revxlp_original:
  #   if: github.event.pull_request.merged == true && github.base_ref == 'main'
  #   needs: build_revxlp_original
  #   uses: iamajoe/keyboards/.github/workflows/release_user_config.yml@main
  #   with:
  #     archive_name: "revxlp_original_firmware"
